version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"

  - package-ecosystem: "npm"
    directory: "/bl-central-server/bl-web-ui"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
          - "angular*"
          - "*angular"
          - "*angular*"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/bl-bridge-server/bl-bridge-humidity-mqtt"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/bl-bridge-server/bl-bridge-temperature-coap"
    schedule:
      interval: "daily"
